name: "CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://cache.garnix.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Verify Flake Evaluation
        run: nix flake check

      - name: Install Home Manager
        run: nix run home-manager -- build --flake .

      - name: Install Dependecies
        run: |
          nix profile install github:srid/nixci

      - name: Build
        run: |
          nixci build
